### ISSUE TITLE
possible typo in install script

### ISSUE THREAD

**Issue by splaisan** [SorenKarst/longread_umi#29]
ref: https://raw.githubusercontent.com/SorenKarst/longread_umi/master/scripts/install_conda.sh

Is it possible that the back-slash before cp be a typo

```
# Modify adapters.py
\cp \
  $CONDA_PREFIX/longread_umi/scripts/adapters.py \
  $CONDA_PREFIX/lib/python3.6/site-packages/porechop/adapters.py

```

no clue if this has negative effects but it looks funny

**Comment by SorenKarst** [comment]
Typo but without consequence. Fixed in 09077c6.
